[package]
name = "desktop-runtime"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anlg-db-app = { workspace = true }
anlg-db-core = { workspace = true }
anlg-db-execute = { workspace = true }
anlg-db-reactive = { workspace = true }
futures = "0.3"
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time", "macros"] }
tokio-util = { workspace = true, features = ["rt"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
tempfile = { workspace = true }
